import { StyleSheet } from 'react-native';

export const authStyles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#eef0f4',
  },
  safeEmbedded: {
    backgroundColor: '#f4f6f0',
  },
  flex: {
    flex: 1,
  },
  frame: {
    flex: 1,
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 12,
  },
  frameEmbedded: {
    paddingTop: 6,
    paddingBottom: 10,
  },
  frameWide: {
    padding: 28,
  },
  split: {
    backgroundColor: '#fff',
    borderRadius: 22,
    overflow: 'hidden',
    shadowColor: '#141c28',
    shadowOpacity: 0.1,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
    elevation: 6,
  },
  splitFill: {
    flex: 1,
  },
  splitWide: {
    flexDirection: 'row',
    minHeight: 640,
    borderRadius: 28,
    maxWidth: 1120,
    width: '100%',
    alignSelf: 'center',
  },
  photoWrap: {
    width: '100%',
    height: 220,
    backgroundColor: '#1f7a3c',
  },
  photoWrapEmbedded: {
    height: 132,
  },
  photoWrapWide: {
    width: '50%',
    height: 'auto',
    minHeight: 640,
    alignSelf: 'stretch',
  },
  photo: {
    width: '100%',
    height: '100%',
  },
  panel: {
    flex: 1,
    paddingHorizontal: 22,
    paddingTop: 20,
    paddingBottom: 20,
    justifyContent: 'flex-start',
  },
  panelWide: {
    flex: 1,
    width: '50%',
    paddingHorizontal: 40,
    paddingTop: 24,
    paddingBottom: 32,
    justifyContent: 'center',
  },
  body: {
    width: '100%',
    maxWidth: 360,
    alignSelf: 'center',
  },
  title: {
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: -0.4,
    lineHeight: 24,
    textAlign: 'center',
    color: '#26392d',
    marginBottom: 8,
  },
  subtitle: {
    textAlign: 'center',
    color: '#737e73',
    fontSize: 14,
    marginBottom: 32,
  },
  label: {
    fontSize: 13,
    fontWeight: '600',
    color: '#26392d',
    marginBottom: 7,
  },
  input: {
    borderWidth: 1,
    borderColor: '#d9dfd6',
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 14,
    color: '#26392d',
    backgroundColor: '#fff',
    marginBottom: 16,
  },
  passwordWrap: {
    position: 'relative',
    marginBottom: 16,
  },
  passwordInput: {
    borderWidth: 1,
    borderColor: '#d9dfd6',
    borderRadius: 999,
    paddingLeft: 16,
    paddingRight: 44,
    paddingVertical: 12,
    fontSize: 14,
    color: '#26392d',
    backgroundColor: '#fff',
  },
  eyeButton: {
    position: 'absolute',
    right: 4,
    top: 0,
    bottom: 0,
    width: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  eyeFallback: {
    color: '#737e73',
    fontSize: 12,
    fontWeight: '600',
  },
  codeInput: {
    borderWidth: 1,
    borderColor: '#d9dfd6',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 28,
    letterSpacing: 10,
    textAlign: 'center',
    color: '#26392d',
    backgroundColor: '#fff',
    marginBottom: 16,
    fontWeight: '700',
  },
  error: {
    backgroundColor: '#fff0ee',
    borderWidth: 1,
    borderColor: '#efd0c8',
    color: '#8c332b',
    borderRadius: 9,
    padding: 13,
    fontSize: 13,
    lineHeight: 20,
    marginBottom: 16,
  },
  notice: {
    backgroundColor: '#edf4e7',
    borderWidth: 1,
    borderColor: '#d8e4cf',
    color: '#26392d',
    borderRadius: 9,
    padding: 13,
    fontSize: 13,
    lineHeight: 20,
    marginBottom: 16,
  },
  primaryButton: {
    backgroundColor: '#1f7a3c',
    borderRadius: 999,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 48,
  },
  primaryButtonPressed: {
    backgroundColor: '#176432',
  },
  primaryButtonText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 15,
  },
  outlineButton: {
    marginTop: 12,
    borderRadius: 999,
    paddingVertical: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#d8ded6',
    backgroundColor: '#fff',
  },
  outlineButtonPressed: {
    backgroundColor: '#e8f6ec',
    borderColor: '#1f7a3c',
  },
  outlineButtonText: {
    color: '#176432',
    fontWeight: '600',
    fontSize: 14,
  },
  hint: {
    fontSize: 12,
    color: '#737e73',
    marginTop: -8,
    marginBottom: 16,
  },
  forgotLink: {
    alignSelf: 'center',
    marginTop: -8,
    marginBottom: 16,
    paddingVertical: 4,
  },
  forgotLinkText: {
    color: '#176432',
    fontSize: 13,
    fontWeight: '600',
  },
  footer: {
    marginTop: 18,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
  },
  footerLink: {
    alignItems: 'center',
  },
  footerLinkText: {
    color: '#8a918c',
    fontSize: 14,
  },
  footerDot: {
    color: '#8a918c',
    fontSize: 14,
  },
  secure: {
    marginTop: 22,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  secureText: {
    color: '#9aa19a',
    fontSize: 12,
  },
});
