export const homeColors = {
  forest: '#173f35',
  forestDeep: '#12332b',
  forestSoft: '#1f4d41',
  leaf: '#2f6b4a',
  mint: '#e7efe3',
  cream: '#f4f6f0',
  paper: '#ffffff',
  ink: '#173f35',
  muted: '#6d7a6f',
  line: '#e3e8df',
  iconWash: '#eef3e8',
  icon: '#3e694b',
  tabIdle: '#8b958c',
};

export const locales = ['sq', 'en', 'de'] as const;
export type HomeLocale = (typeof locales)[number];

export const homeCopy = {
  sq: {
    search: 'Çfarë po kërkon?',
    browseMarket: 'Shfleto Marketplacen',
    popular: 'Kategoritë më të njohura',
    seeAll: 'Shiko të gjitha',
    recommended: 'Produkte të rekomanduara',
    searchMarketplace: 'Kërko në Marketplace',
    sort: 'Rendit',
    newest: 'Më të rejat',
    priceLow: 'Çmimi: i ulët',
    priceHigh: 'Çmimi: i lartë',
    heroText: 'Zbulo produkte të reja dhe të përdorura pranë teje.',
    searchField: 'Kërko',
    categoryField: 'Kategoritë',
    location: 'Qyteti',
    citySearch: 'Kërko qytetin',
    cityEmpty: 'Nuk u gjet asnjë qytet.',
    headline: 'Gjej diçka të mirë.',
    subhead: 'Afër teje.',
    intro: 'Nga gjërat e përditshme te gjetjet e veçanta. Bli dhe shit në komunitetin tënd.',
    country: 'Kosovë',
    city: 'Prishtina',
    sell: 'Publiko Shpallje',
    login: 'Hyr / Regjistrohu',
    account: 'Llogaria ime',
    categories: 'Shfleto sipas kategorisë',
    discoverEyebrow: 'Diçka e re të pret',
    discover: 'Zbulo shpalljet',
    all: 'Shiko të gjitha',
    shops: 'Dyqanet',
    shopsEyebrow: 'BIZNESE NGA KOMUNITETI',
    shopsTitle: 'Dyqane lokale. Njerëz të vërtetë.',
    shopsIntro: 'Shfleto biznese të rishikuara në Kosovë.',
    shopListings: 'Shpalljet',
    shopEmpty: 'Ky dyqan nuk ka shpallje aktive.',
    shopInfo: 'Informacioni i dyqanit',
    shopHoursFallback: 'Kontakto dyqanin për orarin.',
    shopReviewed: 'BIZNES I KONTROLLUAR',
    shopAddress: 'Adresa',
    shopCity: 'Qyteti',
    shopHours: 'Orari',
    shopPhone: 'Telefoni',
    shopEmail: 'Email',
    noResults: 'Nuk u gjet asnjë shpallje.',
    cart: 'Shporta',
    cartEmpty: 'Nuk ke ruajtur asnjë produkt.',
    cartLogin: 'Hyr që të ruash dhe të shohësh të preferuarat.',
    allCities: 'Gjithë Kosova',
    allCategories: 'Të gjitha kategoritë',
    heroTrust1: 'Shpallje të kontrolluara',
    heroTrust2: 'Çmime të mira',
    heroTrust3: 'Nga komuniteti',
    home: 'Home',
    searchTab: 'Kërko',
    publish: 'Publiko',
    messages: 'Mesazhet',
    profile: 'Profili',
  },
  en: {
    search: 'What are you looking for?',
    browseMarket: 'Browse the marketplace',
    popular: 'Popular categories',
    seeAll: 'See all',
    recommended: 'Recommended products',
    searchMarketplace: 'Search the marketplace',
    sort: 'Sort',
    newest: 'Newest',
    priceLow: 'Price: low',
    priceHigh: 'Price: high',
    heroText: 'Discover new and used products near you.',
    searchField: 'Search',
    categoryField: 'Categories',
    location: 'City',
    citySearch: 'Search a city',
    cityEmpty: 'No cities found.',
    headline: 'Find something good.',
    subhead: 'Closer to home.',
    intro: 'From everyday essentials to unexpected finds. Buy and sell in your community.',
    country: 'Kosovo',
    city: 'Prishtina',
    sell: 'Post a listing',
    login: 'Sign in / Register',
    account: 'My account',
    categories: 'Browse by category',
    discoverEyebrow: 'Something new is waiting',
    discover: 'Discover listings',
    all: 'See all',
    shops: 'Shops',
    shopsEyebrow: 'BUSINESSES FROM THE COMMUNITY',
    shopsTitle: 'Local shops. Real people.',
    shopsIntro: 'Explore reviewed businesses across Kosovo.',
    shopListings: 'Available listings',
    shopEmpty: 'This shop has no active listings yet.',
    shopInfo: 'Shop information',
    shopHoursFallback: 'Contact the shop for opening hours.',
    shopReviewed: 'BUSINESS REVIEWED',
    shopAddress: 'Address',
    shopCity: 'City',
    shopHours: 'Opening hours',
    shopPhone: 'Phone',
    shopEmail: 'Email',
    noResults: 'No listings found.',
    cart: 'Cart',
    cartEmpty: 'You have not saved any products.',
    cartLogin: 'Sign in to save and see your favorites.',
    allCities: 'All cities',
    allCategories: 'All categories',
    heroTrust1: 'Reviewed listings',
    heroTrust2: 'Great prices',
    heroTrust3: 'From the community',
    home: 'Home',
    searchTab: 'Search',
    publish: 'Post',
    messages: 'Messages',
    profile: 'Profile',
  },
  de: {
    search: 'Was suchst du?',
    browseMarket: 'Marktplatz ansehen',
    popular: 'Beliebte Kategorien',
    seeAll: 'Alle ansehen',
    recommended: 'Empfohlene Produkte',
    searchMarketplace: 'Im Marktplatz suchen',
    sort: 'Sortieren',
    newest: 'Neueste',
    priceLow: 'Preis: niedrig',
    priceHigh: 'Preis: hoch',
    heroText: 'Entdecke neue und gebrauchte Produkte in deiner Nähe.',
    searchField: 'Suchen',
    categoryField: 'Kategorien',
    location: 'Stadt',
    citySearch: 'Stadt suchen',
    cityEmpty: 'Keine Städte gefunden.',
    headline: 'Entdecke etwas Gutes.',
    subhead: 'Ganz in deiner Nähe.',
    intro: 'Vom Alltäglichen bis zum besonderen Fund. Kaufe und verkaufe in deiner Nachbarschaft.',
    country: 'Kosovo',
    city: 'Prishtina',
    sell: 'Anzeige erstellen',
    login: 'Anmelden / Registrieren',
    account: 'Mein Konto',
    categories: 'Kategorien entdecken',
    discoverEyebrow: 'Etwas Neues wartet',
    discover: 'Anzeigen entdecken',
    all: 'Alle ansehen',
    shops: 'Shops',
    shopsEyebrow: 'BETRIEBE AUS DER NACHBARSCHAFT',
    shopsTitle: 'Lokale Shops. Echte Menschen.',
    shopsIntro: 'Entdecke geprüfte Betriebe im Kosovo.',
    shopListings: 'Anzeigen',
    shopEmpty: 'Dieser Shop hat noch keine aktiven Anzeigen.',
    shopInfo: 'Shop-Informationen',
    shopHoursFallback: 'Frage den Shop nach den Öffnungszeiten.',
    shopReviewed: 'GEPRÜFTES UNTERNEHMEN',
    shopAddress: 'Adresse',
    shopCity: 'Stadt',
    shopHours: 'Öffnungszeiten',
    shopPhone: 'Telefon',
    shopEmail: 'E-Mail',
    noResults: 'Keine Anzeigen gefunden.',
    cart: 'Warenkorb',
    cartEmpty: 'Du hast noch keine Produkte gespeichert.',
    cartLogin: 'Melde dich an, um Favoriten zu speichern.',
    allCities: 'Alle Städte',
    allCategories: 'Alle Kategorien',
    heroTrust1: 'Geprüfte Anzeigen',
    heroTrust2: 'Gute Preise',
    heroTrust3: 'Von der Gemeinschaft',
    home: 'Home',
    searchTab: 'Suche',
    publish: 'Inserat',
    messages: 'Nachrichten',
    profile: 'Profil',
  },
};

export const searchCities = [
  'Prishtinë',
  'Prizren',
  'Pejë',
  'Ferizaj',
  'Gjakovë',
  'Gjilan',
  'Mitrovicë',
  'Vushtrri',
  'Podujevë',
] as const;

export const homeCategories = [
  {
    id: 'tickets',
    label: { sq: 'Bileta', en: 'Tickets', de: 'Tickets & Eintrittskarten' },
    icon: 'ticket',
    image: require('../assets/images/cat-photo-tickets.png'),
  },
  {
    id: 'home',
    label: { sq: 'Shtëpi dhe kopsht', en: 'Home & Garden', de: 'Haus & Garten' },
    icon: 'house',
    image: require('../assets/images/cat-photo-home.png'),
  },
  {
    id: 'business-equipment',
    label: { sq: 'Biznes dhe pajisje', en: 'Business & Equipment', de: 'Gewerbe & Einzelhandel' },
    icon: 'briefcase',
    image: require('../assets/images/cat-photo-business.png'),
  },
  {
    id: 'auto',
    label: { sq: 'Automjete, biçikleta dhe varka', en: 'Auto', de: 'Auto, Rad & Boot' },
    icon: 'car',
    image: require('../assets/images/cat-photo-auto.png'),
  },
  {
    id: 'electronics',
    label: { sq: 'Elektronikë', en: 'Electronics', de: 'Elektronik' },
    icon: 'phone',
    image: require('../assets/images/cat-photo-electronics.png'),
  },
  {
    id: 'family',
    label: { sq: 'Familje, fëmijë dhe bebe', en: 'Family, Kid & Baby', de: 'Familie, Kind & Baby' },
    icon: 'person',
    image: require('../assets/images/cat-photo-family.png'),
  },
  {
    id: 'pets',
    label: { sq: 'Kafshë shtëpiake', en: 'Pets', de: 'Haustiere' },
    icon: 'heart',
    image: require('../assets/images/cat-photo-pets.png'),
  },
  {
    id: 'sports',
    label: { sq: 'Kohë e lirë, hobi dhe fqinjësi', en: 'Free time & hobbies', de: 'Freizeit & Hobby' },
    icon: 'basketball',
    image: require('../assets/images/cat-photo-sports.png'),
  },
  {
    id: 'fashion-beauty',
    label: { sq: 'Modë dhe bukuri', en: 'Mode & Beauty', de: 'Mode & Schönheit' },
    icon: 'bag',
    image: require('../assets/images/cat-photo-fashion.png'),
  },
  {
    id: 'books',
    label: { sq: 'Muzikë, filma dhe libra', en: 'Music, film & books', de: 'Musik, Film & Bücher' },
    icon: 'tv',
    image: require('../assets/images/cat-photo-books.png'),
  },
  {
    id: 'give-away',
    label: { sq: 'Falas', en: 'Give away', de: 'Zu verschenken' },
    icon: 'tag',
    image: require('../assets/images/cat-photo-free.png'),
  },
] as const;

const categoryPhotos = Object.fromEntries(homeCategories.map((item) => [item.id, item.image]));

export function categoryPhoto(id: string) {
  return categoryPhotos[id] ?? homeCategories[0].image;
}
