export const homeColors = {
  forest: '#173f35',
  forestDeep: '#12332b',
  forestSoft: '#1f4d41',
  leaf: '#2f6b4a',
  mint: '#e7efe3',
  cream: '#f4f6f0',
  paper: '#ffffff',
  ink: '#173f35',
  muted: '#6d7a6f',
  line: '#e3e8df',
  iconWash: '#eef3e8',
  icon: '#3e694b',
  tabIdle: '#8b958c',
};

export const locales = ['sq', 'en', 'de'] as const;
export type HomeLocale = (typeof locales)[number];

export const homeCopy = {
  sq: {
    search: 'Çfarë po kërkon?',
    headline: 'Gjej diçka të mirë.',
    subhead: 'Afër teje.',
    intro: 'Nga gjërat e përditshme te gjetjet e veçanta. Bli dhe shit në komunitetin tënd.',
    country: 'Kosovë',
    city: 'Prishtina',
    sell: 'Publiko Shpallje',
    login: 'Hyr / Regjistrohu',
    account: 'Llogaria ime',
    categories: 'Shfleto sipas kategorisë',
    discoverEyebrow: 'Diçka e re të pret',
    discover: 'Zbulo shpalljet',
    all: 'Shiko të gjitha',
    home: 'Home',
    searchTab: 'Kërko',
    publish: 'Publiko',
    messages: 'Mesazhet',
    profile: 'Profili',
  },
  en: {
    search: 'What are you looking for?',
    headline: 'Find something good.',
    subhead: 'Closer to home.',
    intro: 'From everyday essentials to unexpected finds. Buy and sell in your community.',
    country: 'Kosovo',
    city: 'Prishtina',
    sell: 'Post a listing',
    login: 'Sign in / Register',
    account: 'My account',
    categories: 'Browse by category',
    discoverEyebrow: 'Something new is waiting',
    discover: 'Discover listings',
    all: 'See all',
    home: 'Home',
    searchTab: 'Search',
    publish: 'Post',
    messages: 'Messages',
    profile: 'Profile',
  },
  de: {
    search: 'Was suchst du?',
    headline: 'Entdecke etwas Gutes.',
    subhead: 'Ganz in deiner Nähe.',
    intro: 'Vom Alltäglichen bis zum besonderen Fund. Kaufe und verkaufe in deiner Nachbarschaft.',
    country: 'Kosovo',
    city: 'Prishtina',
    sell: 'Anzeige erstellen',
    login: 'Anmelden / Registrieren',
    account: 'Mein Konto',
    categories: 'Kategorien entdecken',
    discoverEyebrow: 'Etwas Neues wartet',
    discover: 'Anzeigen entdecken',
    all: 'Alle ansehen',
    home: 'Home',
    searchTab: 'Suche',
    publish: 'Inserat',
    messages: 'Nachrichten',
    profile: 'Profil',
  },
};

export const homeCategories = [
  { id: 'tickets', label: { sq: 'Bileta', en: 'Tickets', de: 'Tickets' }, icon: 'ticket' },
  {
    id: 'home',
    label: { sq: 'Shtëpi dhe kopsht', en: 'Home & garden', de: 'Haus & Garten' },
    icon: 'sofa',
  },
  {
    id: 'business-equipment',
    label: { sq: 'Biznes dhe pajisje', en: 'Business & equipment', de: 'Gewerbe' },
    icon: 'briefcase',
  },
  {
    id: 'auto',
    label: {
      sq: 'Automjete, biçikleta dhe varka',
      en: 'Cars, bikes & boats',
      de: 'Auto, Rad & Boot',
    },
    icon: 'car',
  },
  {
    id: 'bikes-boats',
    label: { sq: 'Biçikleta dhe varka', en: 'Bikes & boats', de: 'Rad & Boot' },
    icon: 'bicycle',
  },
] as const;
